import {
  PERMISSION_CODES,
  TPermissionCode,
} from 'src/common/constants/permissions';

export const DEFAULT_PROJECT_ROLES = [
  {
    code: 'OWNER',
    name: 'Owner',
    description: 'The owner of the project with full permissions.',
  },
  {
    code: 'ADMIN',
    name: 'Admin',
    description: 'The admin of the project with elevated permissions.',
  },
  {
    code: 'DEVELOPER',
    name: 'Developer',
    description: 'The developer of the project with development permissions.',
  },
  {
    code: 'TESTER',
    name: 'Tester',
    description: 'A member of the project with testing permissions.',
  },
  {
    code: 'VIEWER',
    name: 'Viewer',
    description: 'A member of the project with view-only permissions.',
  },
  {
    code: 'GUEST',
    name: 'Guest',
    description: 'A guest of the project with limited permissions.',
  },
];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, TPermissionCode[]> = {
  OWNER: [
    PERMISSION_CODES.PROJECT_VIEW,
    PERMISSION_CODES.PROJECT_UPDATE,
    PERMISSION_CODES.PROJECT_DELETE,

    PERMISSION_CODES.PROJECT_ARCHIVE,
    PERMISSION_CODES.PROJECT_RESTORE,

    PERMISSION_CODES.PROJECT_MEMBER_ADD,
    PERMISSION_CODES.PROJECT_MEMBER_UPDATE,
    PERMISSION_CODES.PROJECT_MEMBER_REMOVE,

    PERMISSION_CODES.PROJECT_ROLE_MANAGE,

    PERMISSION_CODES.TASK_CREATE,
    PERMISSION_CODES.TASK_VIEW,
    PERMISSION_CODES.TASK_UPDATE,
    PERMISSION_CODES.TASK_DELETE,
    PERMISSION_CODES.TASK_ASSIGN,
    PERMISSION_CODES.TASK_STATUS_UPDATE,
    PERMISSION_CODES.TASK_PRIORITY_UPDATE,
    PERMISSION_CODES.TASK_DUE_DATE_UPDATE,

    PERMISSION_CODES.TASK_COMMENT,

    PERMISSION_CODES.ACTIVITY_VIEW,

    PERMISSION_CODES.REPORT_VIEW,
  ],
  ADMIN: [
    PERMISSION_CODES.PROJECT_VIEW,
    PERMISSION_CODES.PROJECT_UPDATE,

    PERMISSION_CODES.PROJECT_ARCHIVE,

    PERMISSION_CODES.PROJECT_MEMBER_ADD,
    PERMISSION_CODES.PROJECT_MEMBER_UPDATE,
    PERMISSION_CODES.PROJECT_MEMBER_REMOVE,

    PERMISSION_CODES.PROJECT_ROLE_MANAGE,

    PERMISSION_CODES.TASK_CREATE,
    PERMISSION_CODES.TASK_VIEW,
    PERMISSION_CODES.TASK_UPDATE,
    PERMISSION_CODES.TASK_DELETE,
    PERMISSION_CODES.TASK_ASSIGN,
    PERMISSION_CODES.TASK_STATUS_UPDATE,
    PERMISSION_CODES.TASK_PRIORITY_UPDATE,
    PERMISSION_CODES.TASK_DUE_DATE_UPDATE,

    PERMISSION_CODES.TASK_COMMENT,

    PERMISSION_CODES.ACTIVITY_VIEW,

    PERMISSION_CODES.REPORT_VIEW,
  ],
  DEVELOPER: [
    PERMISSION_CODES.PROJECT_VIEW,

    PERMISSION_CODES.TASK_VIEW,
    PERMISSION_CODES.TASK_CREATE,
    PERMISSION_CODES.TASK_UPDATE,
    PERMISSION_CODES.TASK_COMMENT,

    PERMISSION_CODES.ACTIVITY_VIEW,
  ],
  TESTER: [
    PERMISSION_CODES.PROJECT_VIEW,

    PERMISSION_CODES.TASK_VIEW,
    PERMISSION_CODES.TASK_COMMENT,

    PERMISSION_CODES.ACTIVITY_VIEW,
  ],
  VIEWER: [
    PERMISSION_CODES.PROJECT_VIEW,

    PERMISSION_CODES.TASK_VIEW,

    PERMISSION_CODES.ACTIVITY_VIEW,
  ],
  GUEST: [
    PERMISSION_CODES.PROJECT_VIEW,

    PERMISSION_CODES.TASK_VIEW,

    PERMISSION_CODES.ACTIVITY_VIEW,
  ],
};
